<?php
require_once __DIR__ . '/../Connect.php';

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');
header('Content-Type: application/json; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

if (!Input::isPost()) {
    Response::error('ต้องใช้ POST Request เท่านั้น', 405);
}

function getLoginInput(): array {
    $jsonInput = Input::json();
    if (is_array($jsonInput)) {
        return $jsonInput;
    }
    return $_POST;
}

function verifyLoginPassword(string $plainPassword, string $storedHash): bool {
    if (Security::verifyPassword($plainPassword, $storedHash)) {
        return true;
    }

    // Support hashes generated by PostgreSQL crypt() that use "$2a$".
    if (strpos($storedHash, '$2a$') === 0) {
        $normalizedHash = '$2y$' . substr($storedHash, 4);
        return Security::verifyPassword($plainPassword, $normalizedHash);
    }

    return false;
}

function getPendingStatus(PDO $conn, string $studentId): ?string {
    try {
        $stmt = $conn->prepare('SELECT status FROM pending_registrations WHERE student_id = :student_id LIMIT 1');
        $stmt->bindParam(':student_id', $studentId, PDO::PARAM_STR);
        $stmt->execute();
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        if (!$row || !isset($row['status'])) {
            return null;
        }
        return (string)$row['status'];
    } catch (Throwable $e) {
        // If table does not exist yet, skip pending lookup instead of failing login with 500.
        error_log('Login pending lookup skipped: ' . $e->getMessage());
        return null;
    }
}

try {
    $input = getLoginInput();

    if (!isset($input['student_id']) || !isset($input['password'])) {
        Response::error('กรุณากรอกรหัสนักศึกษาและรหัสผ่าน', 400);
    }

    $studentId = Security::sanitize((string)$input['student_id']);
    $password = (string)$input['password'];

    if (!Security::validateStudentId($studentId)) {
        Response::error('รูปแบบรหัสนักศึกษาไม่ถูกต้อง (รหัส 12 หลัก)', 400);
    }
    if (strlen($password) < 6) {
        Response::error('รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร', 400);
    }

    $database = new Database();
    $conn = $database->getConnection();

    $stmt = $conn->prepare('
        SELECT id, student_id, email, fullname, password, role, status
        FROM users
        WHERE student_id = :student_id
        LIMIT 1
    ');
    $stmt->bindParam(':student_id', $studentId, PDO::PARAM_STR);
    $stmt->execute();
    $user = $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$user) {
        $pendingStatus = getPendingStatus($conn, $studentId);
        if ($pendingStatus === 'pending') {
            Response::error('คำขอสมัครสมาชิกของคุณอยู่ระหว่างรอการพิจารณาจากเจ้าหน้าที่', 202);
        }
        if ($pendingStatus === 'rejected') {
            Response::error('คำขอสมัครสมาชิกของคุณถูกปฏิเสธ กรุณาติดต่อเจ้าหน้าที่', 403);
        }
        Response::error('รหัสนักศึกษาหรือรหัสผ่านไม่ถูกต้อง', 401);
    }

    if (($user['status'] ?? '') !== 'active') {
        Response::error('บัญชีของคุณถูกระงับ กรุณาติดต่อผู้ดูแลระบบ', 403);
    }

    if (!verifyLoginPassword($password, (string)$user['password'])) {
        Response::error('รหัสนักศึกษาหรือรหัสผ่านไม่ถูกต้อง', 401);
    }

    Session::start();
    $token = Security::generateToken();

    $userData = [
        'id' => (int)$user['id'],
        'student_id' => (string)$user['student_id'],
        'email' => (string)$user['email'],
        'fullname' => (string)$user['fullname'],
        'role' => (string)$user['role'],
        'status' => (string)$user['status'],
    ];

    Session::set('user_id', $userData['id']);
    Session::set('user_data', $userData);
    Session::set('token', $token);
    Session::set('login_time', time());

    $updateStmt = $conn->prepare('UPDATE users SET updated_at = NOW() WHERE id = :user_id');
    $updateStmt->bindParam(':user_id', $userData['id'], PDO::PARAM_INT);
    $updateStmt->execute();

    Response::success('เข้าสู่ระบบสำเร็จ', [
        'user' => $userData,
        'token' => $token,
        'login_time' => date('Y-m-d H:i:s'),
        'session_expires' => date('Y-m-d H:i:s', time() + (24 * 60 * 60)),
    ]);
} catch (Throwable $e) {
    error_log('Login error: ' . $e->getMessage());
    Response::error('เกิดข้อผิดพลาดในระบบ', 500);
} finally {
    if (isset($database) && $database instanceof Database) {
        $database->closeConnection();
    }
}

